version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  app:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/usr/src
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db